<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { PageResult } from '@srm/shared-types'
import { internalApi } from '../../../api/internal-api'
import { usePermission } from '../../../composables/usePermission'

interface InboxEvent {id:number;eventId:string;sourceSystem:string;objectType:string;objectId:string;objectVersion:number;status:string;attemptCount:number;maxAttempts:number;nextRetryAt:string|null;lastError:string|null;receivedAt:string;processedAt:string|null}
interface OutboxEvent {id:number;eventId:string;objectType:string;objectId:string;objectVersion:number;eventType:string;status:string;attemptCount:number;maxAttempts:number;nextRetryAt:string|null;lastError:string|null;occurredAt:string;createdAt:string}
interface AttemptRecord {id:number;actionCode:string;resultCode:string;reason:string|null;operatorName:string;occurredAt:string;traceId:string}
interface BatchJob {id:number;jobType:string;objectType:string;status:string;totalCount:number;successCount:number;failCount:number;progressPercent:number;resultAttachmentId:number|null;createdBy:string;createdAt:string}
const tab=ref<'inbox'|'outbox'|'jobs'>('inbox'); const loading=ref(false); const page=ref(1);const pageSize=ref(20);const total=ref(0);const rows=ref<(InboxEvent|OutboxEvent)[]>([])
const filter=reactive({status:'',sourceSystem:'',eventType:'',objectType:'',from:'',to:''})
const canRetry=usePermission('system:integration-job:retry')
const detailVisible=ref(false);const detail=ref<InboxEvent|OutboxEvent|null>(null);const attempts=ref<AttemptRecord[]>([])
const batchRows=ref<BatchJob[]>([]);const batchLoading=ref(false);const batchPage=ref(1);const batchTotal=ref(0)
const inboxStatuses=['RECEIVED','PROCESSING','PROCESSED','IGNORED_STALE','FAILED','DEAD']
const outboxStatuses=['READY','PROCESSING','PUBLISHED','FAILED','DEAD','NO_TRANSPORT']
const jobObjectTypes=['PURCHASING_ORGANIZATION','DELIVERY_LOCATION','CATEGORY','UNIT','CURRENCY','TAX_CODE','MATERIAL','EXTERNAL_MAPPING']
async function load(){loading.value=true;try{const q=new URLSearchParams({page:String(page.value),size:String(pageSize.value)});if(filter.status)q.set('status',filter.status);if(filter.sourceSystem&&tab.value==='inbox')q.set('sourceSystem',filter.sourceSystem);if(filter.eventType&&tab.value==='outbox')q.set('eventType',filter.eventType);if(filter.objectType)q.set('objectType',filter.objectType);if(filter.from)q.set('from',new Date(filter.from).toISOString());if(filter.to)q.set('to',new Date(filter.to).toISOString());const r=await internalApi.get<PageResult<InboxEvent|OutboxEvent>>(`/system/${tab.value}-events?${q}`);rows.value=r.items;total.value=r.total}catch(e:unknown){rows.value=[];total.value=0;ElMessage.error((e as Error).message||'加载失败')}finally{loading.value=false}}
async function loadJobs(){batchLoading.value=true;try{const r=await internalApi.get<PageResult<BatchJob>>(`/system/batch-jobs?page=${batchPage.value}&pageSize=10`);batchRows.value=r.items;batchTotal.value=r.total}catch(e:unknown){batchRows.value=[];batchTotal.value=0;ElMessage.error((e as Error).message||'任务加载失败')}finally{batchLoading.value=false}}
function changeTab(){page.value=1;Object.assign(filter,{status:'',sourceSystem:'',eventType:'',objectType:'',from:'',to:''});if(tab.value==='jobs')loadJobs();else load()}
async function retry(row:InboxEvent|OutboxEvent){try{await ElMessageBox.confirm(`确认重试事件 ${row.eventId}？`);await internalApi.post(`/system/${tab.value}-events/${row.id}/retry`);ElMessage.success('已恢复为可处理状态');load()}catch(e){void e}}
function retryable(row:InboxEvent|OutboxEvent){return row.status==='FAILED'&&row.attemptCount<row.maxAttempts}
async function openDetail(row:InboxEvent|OutboxEvent){try{detail.value=await internalApi.get<InboxEvent|OutboxEvent>(`/system/${tab.value}-events/${row.id}`)}catch(e){void e;detail.value=row}try{attempts.value=await internalApi.get<AttemptRecord[]>(`/system/${tab.value}-events/${row.id}/attempts`)??[]}catch(e){void e;attempts.value=[]}detailVisible.value=true}
function inboxOf():InboxEvent|null { return tab.value==='inbox'?detail.value as InboxEvent:null }
function outboxOf():OutboxEvent|null { return tab.value==='outbox'?detail.value as OutboxEvent:null }
const statusType=(s:string)=>s==='PROCESSED'||s==='PUBLISHED'||s==='SUCCEEDED'?'success':s==='FAILED'||s==='DEAD'?'danger':s==='IGNORED_STALE'||s==='NO_TRANSPORT'?'warning':'info'
onMounted(load)
</script>
<template><section class="page"><el-card><el-tabs v-model="tab" @tab-change="changeTab"><el-tab-pane label="Inbox 入站" name="inbox"/><el-tab-pane label="Outbox 出站" name="outbox"/><el-tab-pane label="批处理任务" name="jobs"/></el-tabs><div class="toolbar"><el-select v-if="tab==='inbox'" v-model="filter.status" clearable placeholder="状态" style="width:150px" @change="page=1;load()"><el-option v-for="s in inboxStatuses" :key="s" :label="s" :value="s"/></el-select><el-select v-else-if="tab==='outbox'" v-model="filter.status" clearable placeholder="状态" style="width:150px" @change="page=1;load()"><el-option v-for="s in outboxStatuses" :key="s" :label="s" :value="s"/></el-select><el-input v-if="tab==='inbox'" v-model="filter.sourceSystem" placeholder="来源系统" clearable style="width:140px" @keyup.enter="page=1;load()"/><el-input v-if="tab==='outbox'" v-model="filter.eventType" placeholder="事件类型" clearable style="width:140px" @keyup.enter="page=1;load()"/><el-select v-if="tab!=='jobs'" v-model="filter.objectType" clearable placeholder="对象类型" style="width:170px" @change="page=1;load()"><el-option v-for="x in jobObjectTypes" :key="x" :label="x" :value="x"/></el-select><el-date-picker v-if="tab!=='jobs'" v-model="filter.from" type="datetime" placeholder="开始时间" style="width:160px" @change="page=1;load()"/><el-date-picker v-if="tab!=='jobs'" v-model="filter.to" type="datetime" placeholder="结束时间" style="width:160px" @change="page=1;load()"/><el-button type="primary" @click="page=1;tab==='jobs'?loadJobs():load()">刷新</el-button></div>
<template v-if="tab!=='jobs'"><el-table v-loading="loading" :data="rows" border stripe style="margin-top:16px"><el-table-column prop="eventId" label="事件ID" min-width="190"/><el-table-column v-if="tab==='inbox'" prop="sourceSystem" label="来源系统" width="120"/><el-table-column v-else prop="eventType" label="事件类型" width="150"/><el-table-column prop="objectType" label="对象类型" width="130"/><el-table-column prop="objectId" label="对象ID" width="110"/><el-table-column prop="objectVersion" label="版本" width="70"/><el-table-column label="状态" width="130"><template #default="{row}"><el-tag :type="statusType(row.status)" size="small">{{row.status}}</el-tag></template></el-table-column><el-table-column label="重试" width="90"><template #default="{row}">{{row.attemptCount}} / {{row.maxAttempts}}</template></el-table-column><el-table-column prop="nextRetryAt" label="下次重试" width="170"/><el-table-column prop="lastError" label="失败原因" min-width="170" show-overflow-tooltip/><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="openDetail(row)">详情</el-button><el-button v-if="canRetry&&retryable(row)" link type="primary" @click="retry(row)">重试</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" layout="total, sizes, prev, pager, next" @current-change="load" @size-change="page=1;load()"/></div></template>
<template v-else><el-table v-loading="batchLoading" :data="batchRows" border stripe style="margin-top:16px"><el-table-column prop="id" label="任务ID" width="80"/><el-table-column prop="jobType" label="类型" width="90"/><el-table-column prop="objectType" label="对象" width="190"/><el-table-column label="状态" width="120"><template #default="{row}"><el-tag :type="statusType(row.status)" size="small">{{row.status}}</el-tag></template></el-table-column><el-table-column label="进度" width="120"><template #default="{row}"><el-progress :percentage="row.progressPercent||0"/></template></el-table-column><el-table-column label="数量" width="160"><template #default="{row}">{{row.successCount||0}} 成功 / {{row.failCount||0}} 失败 / {{row.totalCount||0}} 总计</template></el-table-column><el-table-column prop="createdBy" label="创建人" width="120"/><el-table-column prop="createdAt" label="创建时间" width="180"/></el-table><div class="pager"><el-pagination v-model:current-page="batchPage" :page-size="10" :total="batchTotal" layout="total, prev, pager, next" @current-change="loadJobs"/></div></template></el-card>
<el-dialog v-model="detailVisible" :title="'事件详情：'+(detail?.eventId??'')" width="680px"><el-descriptions v-if="detail" :column="2" border size="small"><el-descriptions-item label="事件ID">{{detail.eventId}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusType(detail.status)" size="small">{{detail.status}}</el-tag></el-descriptions-item><el-descriptions-item v-if="inboxOf()" label="来源系统">{{inboxOf()!.sourceSystem}}</el-descriptions-item><el-descriptions-item v-else-if="outboxOf()" label="事件类型">{{outboxOf()!.eventType}}</el-descriptions-item><el-descriptions-item label="对象类型">{{detail.objectType}}</el-descriptions-item><el-descriptions-item label="对象ID">{{detail.objectId}}</el-descriptions-item><el-descriptions-item label="对象版本">{{detail.objectVersion}}</el-descriptions-item><el-descriptions-item label="尝试次数">{{detail.attemptCount}} / {{detail.maxAttempts}}</el-descriptions-item><el-descriptions-item label="下次重试">{{detail.nextRetryAt||'-'}}</el-descriptions-item><el-descriptions-item label="最后错误" :span="2">{{detail.lastError||'-'}}</el-descriptions-item><el-descriptions-item v-if="inboxOf()" label="接收时间" :span="2">{{inboxOf()!.receivedAt}}</el-descriptions-item><el-descriptions-item v-else-if="outboxOf()" label="发生时间" :span="2">{{outboxOf()!.occurredAt}}</el-descriptions-item></el-descriptions><h4 style="margin:14px 0 8px">处理与重试记录</h4><el-table :data="attempts" border size="small" empty-text="暂无处理记录"><el-table-column prop="occurredAt" label="时间" width="170"/><el-table-column prop="actionCode" label="动作" width="190"/><el-table-column label="结果" width="90"><template #default="{row}"><el-tag :type="statusType(row.resultCode)" size="small">{{row.resultCode}}</el-tag></template></el-table-column><el-table-column prop="reason" label="说明" min-width="150" show-overflow-tooltip/><el-table-column prop="traceId" label="traceId" min-width="170" show-overflow-tooltip/></el-table><template #footer><el-button @click="detailVisible=false">关闭</el-button></template></el-dialog></section></template>
<style scoped>.page{padding:24px}.toolbar{display:flex;gap:12px;flex-wrap:wrap}.pager{display:flex;justify-content:flex-end;margin-top:16px}</style>
