// Generated from frontend/module-manifest.json. Do not hand-edit.
import type { RouteComponent, RouteRecordRaw } from 'vue-router'

export const componentRegistry: Readonly<Record<string, RouteComponent>> = {
  "workbench/home/index": () => import('../views/workbench/home/index.vue'),
  "masterdata/organization/index": () => import('../views/masterdata/organization/index.vue'),
  "masterdata/purchasing-organization/index": () => import('../views/masterdata/purchasing-organization/index.vue'),
  "masterdata/plant-receiving/index": () => import('../views/masterdata/plant-receiving/index.vue'),
  "masterdata/material/index": () => import('../views/masterdata/material/index.vue'),
  "masterdata/category/index": () => import('../views/masterdata/category/index.vue'),
  "masterdata/unit-currency-tax/index": () => import('../views/masterdata/unit-currency-tax/index.vue'),
  "masterdata/delivery-location/index": () => import('../views/masterdata/delivery-location/index.vue'),
  "masterdata/external-mapping/index": () => import('../views/masterdata/external-mapping/index.vue'),
  "system/department/index": () => import('../views/system/department/index.vue'),
  "system/position/index": () => import('../views/system/position/index.vue'),
  "system/user/index": () => import('../views/system/user/index.vue'),
  "system/role/index": () => import('../views/system/role/index.vue'),
  "system/function-permission/index": () => import('../views/system/function-permission/index.vue'),
  "system/data-permission/index": () => import('../views/system/data-permission/index.vue'),
  "system/workflow/index": () => import('../views/system/workflow/index.vue'),
  "system/dictionary-parameter/index": () => import('../views/system/dictionary-parameter/index.vue'),
  "system/template-attachment/index": () => import('../views/system/template-attachment/index.vue'),
  "system/message/index": () => import('../views/system/message/index.vue'),
  "system/audit-log/index": () => import('../views/system/audit-log/index.vue'),
  "system/integration-job/index": () => import('../views/system/integration-job/index.vue'),
}

export const featureRoutes: RouteRecordRaw[] = [
  {
    path: "/workbench",
    name: "MENU_WORKBENCH_HOME",
    component: componentRegistry["workbench/home/index"],
    meta: {
      title: "工作台首页",
      domainLabel: "工作台",
      domainCode: "workbench",
      menuCode: "MENU_WORKBENCH_HOME",
      permission: "workbench:home:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/organization",
    name: "MENU_MASTERDATA_ORGANIZATION",
    component: componentRegistry["masterdata/organization/index"],
    meta: {
      title: "企业组织",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_ORGANIZATION",
      permission: "masterdata:organization:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/purchasing-organization",
    name: "MENU_MASTERDATA_PURCHASING_ORG",
    component: componentRegistry["masterdata/purchasing-organization/index"],
    meta: {
      title: "采购组织",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_PURCHASING_ORG",
      permission: "masterdata:purchasing-organization:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/plant-receiving",
    name: "MENU_MASTERDATA_PLANT_RECEIVING",
    component: componentRegistry["masterdata/plant-receiving/index"],
    meta: {
      title: "工厂/收货地点",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_PLANT_RECEIVING",
      permission: "masterdata:plant-receiving:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/material",
    name: "MENU_MASTERDATA_MATERIAL",
    component: componentRegistry["masterdata/material/index"],
    meta: {
      title: "物料",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_MATERIAL",
      permission: "masterdata:material:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/category",
    name: "MENU_MASTERDATA_CATEGORY",
    component: componentRegistry["masterdata/category/index"],
    meta: {
      title: "品类",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_CATEGORY",
      permission: "masterdata:category:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/unit-currency-tax",
    name: "MENU_MASTERDATA_UNIT_CURRENCY_TAX",
    component: componentRegistry["masterdata/unit-currency-tax/index"],
    meta: {
      title: "单位/币种/税码",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_UNIT_CURRENCY_TAX",
      permission: "masterdata:unit-currency-tax:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/delivery-location",
    name: "MENU_MASTERDATA_DELIVERY_LOCATION",
    component: componentRegistry["masterdata/delivery-location/index"],
    meta: {
      title: "交付地点",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_DELIVERY_LOCATION",
      permission: "masterdata:delivery-location:view",
      requiresAuth: true,
    },
  },
  {
    path: "/masterdata/external-mapping",
    name: "MENU_MASTERDATA_EXTERNAL_MAPPING",
    component: componentRegistry["masterdata/external-mapping/index"],
    meta: {
      title: "外围映射",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_EXTERNAL_MAPPING",
      permission: "masterdata:external-mapping:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/department",
    name: "MENU_SYSTEM_DEPARTMENT",
    component: componentRegistry["system/department/index"],
    meta: {
      title: "部门管理",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_DEPARTMENT",
      permission: "system:department:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/position",
    name: "MENU_SYSTEM_POSITION",
    component: componentRegistry["system/position/index"],
    meta: {
      title: "岗位管理",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_POSITION",
      permission: "system:position:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/user",
    name: "MENU_SYSTEM_USER",
    component: componentRegistry["system/user/index"],
    meta: {
      title: "内部用户",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_USER",
      permission: "system:user:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/role",
    name: "MENU_SYSTEM_ROLE",
    component: componentRegistry["system/role/index"],
    meta: {
      title: "角色管理",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_ROLE",
      permission: "system:role:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/function-permission",
    name: "MENU_SYSTEM_FUNCTION_PERMISSION",
    component: componentRegistry["system/function-permission/index"],
    meta: {
      title: "功能权限",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_FUNCTION_PERMISSION",
      permission: "system:function-permission:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/data-permission",
    name: "MENU_SYSTEM_DATA_PERMISSION",
    component: componentRegistry["system/data-permission/index"],
    meta: {
      title: "数据权限",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_DATA_PERMISSION",
      permission: "system:data-permission:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/workflow",
    name: "MENU_SYSTEM_WORKFLOW",
    component: componentRegistry["system/workflow/index"],
    meta: {
      title: "流程",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_WORKFLOW",
      permission: "system:workflow:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/dictionary-parameter",
    name: "MENU_SYSTEM_DICTIONARY_PARAMETER",
    component: componentRegistry["system/dictionary-parameter/index"],
    meta: {
      title: "字典参数",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_DICTIONARY_PARAMETER",
      permission: "system:dictionary-parameter:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/template-attachment",
    name: "MENU_SYSTEM_TEMPLATE_ATTACHMENT",
    component: componentRegistry["system/template-attachment/index"],
    meta: {
      title: "模板附件",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_TEMPLATE_ATTACHMENT",
      permission: "system:template-attachment:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/message",
    name: "MENU_SYSTEM_MESSAGE",
    component: componentRegistry["system/message/index"],
    meta: {
      title: "消息",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_MESSAGE",
      permission: "system:message:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/audit-log",
    name: "MENU_SYSTEM_AUDIT_LOG",
    component: componentRegistry["system/audit-log/index"],
    meta: {
      title: "审计日志",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_AUDIT_LOG",
      permission: "system:audit-log:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/integration-job",
    name: "MENU_SYSTEM_INTEGRATION_JOB",
    component: componentRegistry["system/integration-job/index"],
    meta: {
      title: "接口与任务监控",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_INTEGRATION_JOB",
      permission: "system:integration-job:view",
      requiresAuth: true,
    },
  },
]

