// Generated from frontend/module-manifest.json. Do not hand-edit.
import type { RouteComponent, RouteRecordRaw } from 'vue-router'

export const componentRegistry: Readonly<Record<string, RouteComponent>> = {
  "workbench/home/index": () => import('../views/workbench/home/index.vue'),
  "supplier/pool/index": () => import('../views/supplier/pool/index.vue'),
  "supplier/registration/index": () => import('../views/supplier/registration/index.vue'),
  "supplier/profile/index": () => import('../views/supplier/profile/index.vue'),
  "supplier/admission/index": () => import('../views/supplier/admission/index.vue'),
  "supplier/qualification/index": () => import('../views/supplier/qualification/index.vue'),
  "supplier/review-change/index": () => import('../views/supplier/review-change/index.vue'),
  "supplier/restriction/index": () => import('../views/supplier/restriction/index.vue'),
  "supplier/user/index": () => import('../views/supplier/user/index.vue'),
  "sourcing/requirement/index": () => import('../views/sourcing/requirement/index.vue'),
  "sourcing/project/index": () => import('../views/sourcing/project/index.vue'),
  "sourcing/rfx/index": () => import('../views/sourcing/rfx/index.vue'),
  "sourcing/bid-auction/index": () => import('../views/sourcing/bid-auction/index.vue'),
  "sourcing/quotation/index": () => import('../views/sourcing/quotation/index.vue'),
  "sourcing/clarification/index": () => import('../views/sourcing/clarification/index.vue'),
  "sourcing/evaluation-award/index": () => import('../views/sourcing/evaluation-award/index.vue'),
  "sourcing/conversion/index": () => import('../views/sourcing/conversion/index.vue'),
  "contract/contract/index": () => import('../views/contract/contract/index.vue'),
  "contract/agreement/index": () => import('../views/contract/agreement/index.vue'),
  "contract/purchasing-basis/index": () => import('../views/contract/purchasing-basis/index.vue'),
  "contract/price-condition/index": () => import('../views/contract/price-condition/index.vue'),
  "contract/price-version/index": () => import('../views/contract/price-version/index.vue'),
  "contract/renewal-termination/index": () => import('../views/contract/renewal-termination/index.vue'),
  "contract/performance-alert/index": () => import('../views/contract/performance-alert/index.vue'),
  "source/candidate/index": () => import('../views/source/candidate/index.vue'),
  "source/trial-conditional/index": () => import('../views/source/trial-conditional/index.vue'),
  "source/approved/index": () => import('../views/source/approved/index.vue'),
  "source/quota/index": () => import('../views/source/quota/index.vue'),
  "source/capacity/index": () => import('../views/source/capacity/index.vue'),
  "source/restriction/index": () => import('../views/source/restriction/index.vue'),
  "source/history/index": () => import('../views/source/history/index.vue'),
  "procurement/requirement/index": () => import('../views/procurement/requirement/index.vue'),
  "procurement/matching/index": () => import('../views/procurement/matching/index.vue'),
  "procurement/gap/index": () => import('../views/procurement/gap/index.vue'),
  "procurement/allocation/index": () => import('../views/procurement/allocation/index.vue'),
  "procurement/purchase-order/index": () => import('../views/procurement/purchase-order/index.vue'),
  "procurement/confirmation/index": () => import('../views/procurement/confirmation/index.vue'),
  "procurement/change-cancel/index": () => import('../views/procurement/change-cancel/index.vue'),
  "delivery/plan/index": () => import('../views/delivery/plan/index.vue'),
  "delivery/asn/index": () => import('../views/delivery/asn/index.vue'),
  "delivery/packaging-label/index": () => import('../views/delivery/packaging-label/index.vue'),
  "delivery/shipment/index": () => import('../views/delivery/shipment/index.vue'),
  "delivery/appointment/index": () => import('../views/delivery/appointment/index.vue'),
  "delivery/receipt/index": () => import('../views/delivery/receipt/index.vue'),
  "delivery/quantity-difference/index": () => import('../views/delivery/quantity-difference/index.vue'),
  "delivery/return/index": () => import('../views/delivery/return/index.vue'),
  "quality/audit/index": () => import('../views/quality/audit/index.vue'),
  "quality/material-qualification/index": () => import('../views/quality/material-qualification/index.vue'),
  "quality/sample-trial/index": () => import('../views/quality/sample-trial/index.vue'),
  "quality/production-approval/index": () => import('../views/quality/production-approval/index.vue'),
  "quality/inspection/index": () => import('../views/quality/inspection/index.vue'),
  "quality/issue/index": () => import('../views/quality/issue/index.vue'),
  "quality/scar-8d/index": () => import('../views/quality/scar-8d/index.vue'),
  "quality/rework-reinspection/index": () => import('../views/quality/rework-reinspection/index.vue'),
  "quality/supplier-change/index": () => import('../views/quality/supplier-change/index.vue'),
  "settlement/reconciliation/index": () => import('../views/settlement/reconciliation/index.vue'),
  "settlement/difference/index": () => import('../views/settlement/difference/index.vue'),
  "settlement/invoice/index": () => import('../views/settlement/invoice/index.vue'),
  "settlement/payment-request/index": () => import('../views/settlement/payment-request/index.vue'),
  "settlement/payable-status/index": () => import('../views/settlement/payable-status/index.vue'),
  "settlement/payment-result/index": () => import('../views/settlement/payment-result/index.vue'),
  "performance/indicator-model/index": () => import('../views/performance/indicator-model/index.vue'),
  "performance/score/index": () => import('../views/performance/score/index.vue'),
  "performance/rating/index": () => import('../views/performance/rating/index.vue'),
  "performance/risk/index": () => import('../views/performance/risk/index.vue'),
  "performance/alert/index": () => import('../views/performance/alert/index.vue'),
  "performance/improvement/index": () => import('../views/performance/improvement/index.vue'),
  "performance/supply-decision/index": () => import('../views/performance/supply-decision/index.vue'),
  "performance/second-source/index": () => import('../views/performance/second-source/index.vue'),
  "masterdata/organization/index": () => import('../views/masterdata/organization/index.vue'),
  "masterdata/purchasing-organization/index": () => import('../views/masterdata/purchasing-organization/index.vue'),
  "masterdata/plant-receiving/index": () => import('../views/masterdata/plant-receiving/index.vue'),
  "masterdata/material/index": () => import('../views/masterdata/material/index.vue'),
  "masterdata/category/index": () => import('../views/masterdata/category/index.vue'),
  "masterdata/unit-currency-tax/index": () => import('../views/masterdata/unit-currency-tax/index.vue'),
  "masterdata/delivery-location/index": () => import('../views/masterdata/delivery-location/index.vue'),
  "masterdata/external-mapping/index": () => import('../views/masterdata/external-mapping/index.vue'),
  "system/user/index": () => import('../views/system/user/index.vue'),
  "system/role/index": () => import('../views/system/role/index.vue'),
  "system/permission/index": () => import('../views/system/permission/index.vue'),
  "system/workflow/index": () => import('../views/system/workflow/index.vue'),
  "system/dictionary-parameter/index": () => import('../views/system/dictionary-parameter/index.vue'),
  "system/template-attachment/index": () => import('../views/system/template-attachment/index.vue'),
  "system/message/index": () => import('../views/system/message/index.vue'),
  "system/audit-log/index": () => import('../views/system/audit-log/index.vue'),
  "system/integration-job/index": () => import('../views/system/integration-job/index.vue'),
}

export const featureRoutes: RouteRecordRaw[] = [
  {
    path: "/workbench",
    name: "MENU_WORKBENCH_HOME",
    component: componentRegistry["workbench/home/index"],
    meta: {
      title: "工作台首页",
      domainLabel: "工作台",
      domainCode: "workbench",
      menuCode: "MENU_WORKBENCH_HOME",
      permission: "workbench:home:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/pool",
    name: "MENU_SUPPLIER_POOL",
    component: componentRegistry["supplier/pool/index"],
    meta: {
      title: "供应商资源池",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_POOL",
      permission: "supplier:pool:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/registrations",
    name: "MENU_SUPPLIER_REGISTRATION",
    component: componentRegistry["supplier/registration/index"],
    meta: {
      title: "注册申请",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_REGISTRATION",
      permission: "supplier:registration:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/profiles",
    name: "MENU_SUPPLIER_PROFILE",
    component: componentRegistry["supplier/profile/index"],
    meta: {
      title: "供应商档案",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_PROFILE",
      permission: "supplier:profile:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/admissions",
    name: "MENU_SUPPLIER_ADMISSION",
    component: componentRegistry["supplier/admission/index"],
    meta: {
      title: "准入与认证",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_ADMISSION",
      permission: "supplier:admission:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/qualifications",
    name: "MENU_SUPPLIER_QUALIFICATION",
    component: componentRegistry["supplier/qualification/index"],
    meta: {
      title: "资质证照",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_QUALIFICATION",
      permission: "supplier:qualification:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/reviews-changes",
    name: "MENU_SUPPLIER_REVIEW_CHANGE",
    component: componentRegistry["supplier/review-change/index"],
    meta: {
      title: "复审与变更",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_REVIEW_CHANGE",
      permission: "supplier:review-change:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/restrictions",
    name: "MENU_SUPPLIER_RESTRICTION",
    component: componentRegistry["supplier/restriction/index"],
    meta: {
      title: "冻结与退出",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_RESTRICTION",
      permission: "supplier:restriction:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supplier/users",
    name: "MENU_SUPPLIER_USER",
    component: componentRegistry["supplier/user/index"],
    meta: {
      title: "供应商用户",
      domainLabel: "供应商管理",
      domainCode: "supplier",
      menuCode: "MENU_SUPPLIER_USER",
      permission: "supplier:user:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/requirements",
    name: "MENU_SOURCING_REQUIREMENT",
    component: componentRegistry["sourcing/requirement/index"],
    meta: {
      title: "寻源需求",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_REQUIREMENT",
      permission: "sourcing:requirement:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/projects",
    name: "MENU_SOURCING_PROJECT",
    component: componentRegistry["sourcing/project/index"],
    meta: {
      title: "寻源项目",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_PROJECT",
      permission: "sourcing:project:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/rfx",
    name: "MENU_SOURCING_RFX",
    component: componentRegistry["sourcing/rfx/index"],
    meta: {
      title: "RFI/RFQ",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_RFX",
      permission: "sourcing:rfx:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/bids-auctions",
    name: "MENU_SOURCING_BID_AUCTION",
    component: componentRegistry["sourcing/bid-auction/index"],
    meta: {
      title: "招投标/竞价",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_BID_AUCTION",
      permission: "sourcing:bid-auction:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/quotations",
    name: "MENU_SOURCING_QUOTATION",
    component: componentRegistry["sourcing/quotation/index"],
    meta: {
      title: "供应商报价",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_QUOTATION",
      permission: "sourcing:quotation:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/clarifications",
    name: "MENU_SOURCING_CLARIFICATION",
    component: componentRegistry["sourcing/clarification/index"],
    meta: {
      title: "澄清答疑",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_CLARIFICATION",
      permission: "sourcing:clarification:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/evaluations-awards",
    name: "MENU_SOURCING_EVALUATION_AWARD",
    component: componentRegistry["sourcing/evaluation-award/index"],
    meta: {
      title: "评审与定标",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_EVALUATION_AWARD",
      permission: "sourcing:evaluation-award:view",
      requiresAuth: true,
    },
  },
  {
    path: "/sourcing/conversions",
    name: "MENU_SOURCING_CONVERSION",
    component: componentRegistry["sourcing/conversion/index"],
    meta: {
      title: "中选转化任务",
      domainLabel: "战略寻源",
      domainCode: "sourcing",
      menuCode: "MENU_SOURCING_CONVERSION",
      permission: "sourcing:conversion:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/contracts",
    name: "MENU_CONTRACT_CONTRACT",
    component: componentRegistry["contract/contract/index"],
    meta: {
      title: "合同台账",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_CONTRACT",
      permission: "contract:contract:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/agreements",
    name: "MENU_CONTRACT_AGREEMENT",
    component: componentRegistry["contract/agreement/index"],
    meta: {
      title: "框架/补充协议",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_AGREEMENT",
      permission: "contract:agreement:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/purchasing-bases",
    name: "MENU_CONTRACT_PURCHASING_BASIS",
    component: componentRegistry["contract/purchasing-basis/index"],
    meta: {
      title: "采购依据",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_PURCHASING_BASIS",
      permission: "contract:purchasing-basis:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/price-conditions",
    name: "MENU_CONTRACT_PRICE_CONDITION",
    component: componentRegistry["contract/price-condition/index"],
    meta: {
      title: "价格条件",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_PRICE_CONDITION",
      permission: "contract:price-condition:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/price-versions",
    name: "MENU_CONTRACT_PRICE_VERSION",
    component: componentRegistry["contract/price-version/index"],
    meta: {
      title: "调价与版本",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_PRICE_VERSION",
      permission: "contract:price-version:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/renewals-terminations",
    name: "MENU_CONTRACT_RENEWAL_TERMINATION",
    component: componentRegistry["contract/renewal-termination/index"],
    meta: {
      title: "续签/终止",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_RENEWAL_TERMINATION",
      permission: "contract:renewal-termination:view",
      requiresAuth: true,
    },
  },
  {
    path: "/contract/performance-alerts",
    name: "MENU_CONTRACT_PERFORMANCE_ALERT",
    component: componentRegistry["contract/performance-alert/index"],
    meta: {
      title: "履约与临期预警",
      domainLabel: "合同与价格管理",
      domainCode: "contract",
      menuCode: "MENU_CONTRACT_PERFORMANCE_ALERT",
      permission: "contract:performance-alert:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/candidates",
    name: "MENU_SOURCE_CANDIDATE",
    component: componentRegistry["source/candidate/index"],
    meta: {
      title: "候选供应源",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_CANDIDATE",
      permission: "source:candidate:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/trial-conditional",
    name: "MENU_SOURCE_TRIAL_CONDITIONAL",
    component: componentRegistry["source/trial-conditional/index"],
    meta: {
      title: "试制/条件供应源",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_TRIAL_CONDITIONAL",
      permission: "source:trial-conditional:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/approved",
    name: "MENU_SOURCE_APPROVED",
    component: componentRegistry["source/approved/index"],
    meta: {
      title: "正式供应源",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_APPROVED",
      permission: "source:approved:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/quotas",
    name: "MENU_SOURCE_QUOTA",
    component: componentRegistry["source/quota/index"],
    meta: {
      title: "供应配额",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_QUOTA",
      permission: "source:quota:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/capacities",
    name: "MENU_SOURCE_CAPACITY",
    component: componentRegistry["source/capacity/index"],
    meta: {
      title: "能力与交期",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_CAPACITY",
      permission: "source:capacity:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/restrictions",
    name: "MENU_SOURCE_RESTRICTION",
    component: componentRegistry["source/restriction/index"],
    meta: {
      title: "限制/暂停",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_RESTRICTION",
      permission: "source:restriction:view",
      requiresAuth: true,
    },
  },
  {
    path: "/supply-source/history",
    name: "MENU_SOURCE_HISTORY",
    component: componentRegistry["source/history/index"],
    meta: {
      title: "供应源变更历史",
      domainLabel: "供应源管理",
      domainCode: "source",
      menuCode: "MENU_SOURCE_HISTORY",
      permission: "source:history:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/requirements",
    name: "MENU_PROCUREMENT_REQUIREMENT",
    component: componentRegistry["procurement/requirement/index"],
    meta: {
      title: "采购需求",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_REQUIREMENT",
      permission: "procurement:requirement:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/matching",
    name: "MENU_PROCUREMENT_MATCHING",
    component: componentRegistry["procurement/matching/index"],
    meta: {
      title: "供应源匹配",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_MATCHING",
      permission: "procurement:matching:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/gaps",
    name: "MENU_PROCUREMENT_GAP",
    component: componentRegistry["procurement/gap/index"],
    meta: {
      title: "需求缺口",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_GAP",
      permission: "procurement:gap:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/allocations",
    name: "MENU_PROCUREMENT_ALLOCATION",
    component: componentRegistry["procurement/allocation/index"],
    meta: {
      title: "需求分配",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_ALLOCATION",
      permission: "procurement:allocation:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/purchase-orders",
    name: "MENU_PROCUREMENT_PURCHASE_ORDER",
    component: componentRegistry["procurement/purchase-order/index"],
    meta: {
      title: "采购订单",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_PURCHASE_ORDER",
      permission: "procurement:purchase-order:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/confirmations",
    name: "MENU_PROCUREMENT_CONFIRMATION",
    component: componentRegistry["procurement/confirmation/index"],
    meta: {
      title: "订单确认",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_CONFIRMATION",
      permission: "procurement:confirmation:view",
      requiresAuth: true,
    },
  },
  {
    path: "/procurement/changes-cancellations",
    name: "MENU_PROCUREMENT_CHANGE_CANCEL",
    component: componentRegistry["procurement/change-cancel/index"],
    meta: {
      title: "订单变更/取消",
      domainLabel: "采购协同",
      domainCode: "procurement",
      menuCode: "MENU_PROCUREMENT_CHANGE_CANCEL",
      permission: "procurement:change-cancel:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/plans",
    name: "MENU_DELIVERY_PLAN",
    component: componentRegistry["delivery/plan/index"],
    meta: {
      title: "交付计划",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_PLAN",
      permission: "delivery:plan:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/asn",
    name: "MENU_DELIVERY_ASN",
    component: componentRegistry["delivery/asn/index"],
    meta: {
      title: "ASN",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_ASN",
      permission: "delivery:asn:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/packaging-labels",
    name: "MENU_DELIVERY_PACKAGING_LABEL",
    component: componentRegistry["delivery/packaging-label/index"],
    meta: {
      title: "包装与标签",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_PACKAGING_LABEL",
      permission: "delivery:packaging-label:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/shipments",
    name: "MENU_DELIVERY_SHIPMENT",
    component: componentRegistry["delivery/shipment/index"],
    meta: {
      title: "发运/在途",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_SHIPMENT",
      permission: "delivery:shipment:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/appointments",
    name: "MENU_DELIVERY_APPOINTMENT",
    component: componentRegistry["delivery/appointment/index"],
    meta: {
      title: "到货预约",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_APPOINTMENT",
      permission: "delivery:appointment:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/receipts",
    name: "MENU_DELIVERY_RECEIPT",
    component: componentRegistry["delivery/receipt/index"],
    meta: {
      title: "收货反馈",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_RECEIPT",
      permission: "delivery:receipt:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/quantity-differences",
    name: "MENU_DELIVERY_QUANTITY_DIFFERENCE",
    component: componentRegistry["delivery/quantity-difference/index"],
    meta: {
      title: "数量差异",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_QUANTITY_DIFFERENCE",
      permission: "delivery:quantity-difference:view",
      requiresAuth: true,
    },
  },
  {
    path: "/delivery/returns",
    name: "MENU_DELIVERY_RETURN",
    component: componentRegistry["delivery/return/index"],
    meta: {
      title: "退货发运",
      domainLabel: "交付与收货协同",
      domainCode: "delivery",
      menuCode: "MENU_DELIVERY_RETURN",
      permission: "delivery:return:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/audits",
    name: "MENU_QUALITY_AUDIT",
    component: componentRegistry["quality/audit/index"],
    meta: {
      title: "审核计划",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_AUDIT",
      permission: "quality:audit:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/material-qualifications",
    name: "MENU_QUALITY_MATERIAL_QUALIFICATION",
    component: componentRegistry["quality/material-qualification/index"],
    meta: {
      title: "物料资格",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_MATERIAL_QUALIFICATION",
      permission: "quality:material-qualification:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/samples-trials",
    name: "MENU_QUALITY_SAMPLE_TRIAL",
    component: componentRegistry["quality/sample-trial/index"],
    meta: {
      title: "样件/试制",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_SAMPLE_TRIAL",
      permission: "quality:sample-trial:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/production-approvals",
    name: "MENU_QUALITY_PRODUCTION_APPROVAL",
    component: componentRegistry["quality/production-approval/index"],
    meta: {
      title: "量产认可",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_PRODUCTION_APPROVAL",
      permission: "quality:production-approval:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/inspections",
    name: "MENU_QUALITY_INSPECTION",
    component: componentRegistry["quality/inspection/index"],
    meta: {
      title: "检验结果",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_INSPECTION",
      permission: "quality:inspection:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/issues",
    name: "MENU_QUALITY_ISSUE",
    component: componentRegistry["quality/issue/index"],
    meta: {
      title: "质量异常",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_ISSUE",
      permission: "quality:issue:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/scar-8d",
    name: "MENU_QUALITY_SCAR_8D",
    component: componentRegistry["quality/scar-8d/index"],
    meta: {
      title: "SCAR/8D",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_SCAR_8D",
      permission: "quality:scar-8d:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/rework-reinspection",
    name: "MENU_QUALITY_REWORK_REINSPECTION",
    component: componentRegistry["quality/rework-reinspection/index"],
    meta: {
      title: "退货/返工/复验",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_REWORK_REINSPECTION",
      permission: "quality:rework-reinspection:view",
      requiresAuth: true,
    },
  },
  {
    path: "/quality/supplier-changes",
    name: "MENU_QUALITY_SUPPLIER_CHANGE",
    component: componentRegistry["quality/supplier-change/index"],
    meta: {
      title: "供应商变更",
      domainLabel: "供应商质量管理",
      domainCode: "quality",
      menuCode: "MENU_QUALITY_SUPPLIER_CHANGE",
      permission: "quality:supplier-change:view",
      requiresAuth: true,
    },
  },
  {
    path: "/settlement/reconciliations",
    name: "MENU_SETTLEMENT_RECONCILIATION",
    component: componentRegistry["settlement/reconciliation/index"],
    meta: {
      title: "对账单",
      domainLabel: "对账与结算协同",
      domainCode: "settlement",
      menuCode: "MENU_SETTLEMENT_RECONCILIATION",
      permission: "settlement:reconciliation:view",
      requiresAuth: true,
    },
  },
  {
    path: "/settlement/differences",
    name: "MENU_SETTLEMENT_DIFFERENCE",
    component: componentRegistry["settlement/difference/index"],
    meta: {
      title: "差异处理",
      domainLabel: "对账与结算协同",
      domainCode: "settlement",
      menuCode: "MENU_SETTLEMENT_DIFFERENCE",
      permission: "settlement:difference:view",
      requiresAuth: true,
    },
  },
  {
    path: "/settlement/invoices",
    name: "MENU_SETTLEMENT_INVOICE",
    component: componentRegistry["settlement/invoice/index"],
    meta: {
      title: "发票协同",
      domainLabel: "对账与结算协同",
      domainCode: "settlement",
      menuCode: "MENU_SETTLEMENT_INVOICE",
      permission: "settlement:invoice:view",
      requiresAuth: true,
    },
  },
  {
    path: "/settlement/payment-requests",
    name: "MENU_SETTLEMENT_PAYMENT_REQUEST",
    component: componentRegistry["settlement/payment-request/index"],
    meta: {
      title: "请款材料",
      domainLabel: "对账与结算协同",
      domainCode: "settlement",
      menuCode: "MENU_SETTLEMENT_PAYMENT_REQUEST",
      permission: "settlement:payment-request:view",
      requiresAuth: true,
    },
  },
  {
    path: "/settlement/payable-status",
    name: "MENU_SETTLEMENT_PAYABLE_STATUS",
    component: componentRegistry["settlement/payable-status/index"],
    meta: {
      title: "应付状态",
      domainLabel: "对账与结算协同",
      domainCode: "settlement",
      menuCode: "MENU_SETTLEMENT_PAYABLE_STATUS",
      permission: "settlement:payable-status:view",
      requiresAuth: true,
    },
  },
  {
    path: "/settlement/payment-results",
    name: "MENU_SETTLEMENT_PAYMENT_RESULT",
    component: componentRegistry["settlement/payment-result/index"],
    meta: {
      title: "付款结果",
      domainLabel: "对账与结算协同",
      domainCode: "settlement",
      menuCode: "MENU_SETTLEMENT_PAYMENT_RESULT",
      permission: "settlement:payment-result:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/indicator-models",
    name: "MENU_PERFORMANCE_INDICATOR_MODEL",
    component: componentRegistry["performance/indicator-model/index"],
    meta: {
      title: "指标模型",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_INDICATOR_MODEL",
      permission: "performance:indicator-model:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/scores",
    name: "MENU_PERFORMANCE_SCORE",
    component: componentRegistry["performance/score/index"],
    meta: {
      title: "绩效评分",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_SCORE",
      permission: "performance:score:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/ratings",
    name: "MENU_PERFORMANCE_RATING",
    component: componentRegistry["performance/rating/index"],
    meta: {
      title: "评级结果",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_RATING",
      permission: "performance:rating:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/risks",
    name: "MENU_PERFORMANCE_RISK",
    component: componentRegistry["performance/risk/index"],
    meta: {
      title: "风险台账",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_RISK",
      permission: "performance:risk:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/alerts",
    name: "MENU_PERFORMANCE_ALERT",
    component: componentRegistry["performance/alert/index"],
    meta: {
      title: "预警事件",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_ALERT",
      permission: "performance:alert:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/improvements",
    name: "MENU_PERFORMANCE_IMPROVEMENT",
    component: componentRegistry["performance/improvement/index"],
    meta: {
      title: "改善计划",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_IMPROVEMENT",
      permission: "performance:improvement:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/supply-decisions",
    name: "MENU_PERFORMANCE_SUPPLY_DECISION",
    component: componentRegistry["performance/supply-decision/index"],
    meta: {
      title: "供应决策",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_SUPPLY_DECISION",
      permission: "performance:supply-decision:view",
      requiresAuth: true,
    },
  },
  {
    path: "/performance/second-source-plans",
    name: "MENU_PERFORMANCE_SECOND_SOURCE",
    component: componentRegistry["performance/second-source/index"],
    meta: {
      title: "第二供应源计划",
      domainLabel: "绩效与风险管理",
      domainCode: "performance",
      menuCode: "MENU_PERFORMANCE_SECOND_SOURCE",
      permission: "performance:second-source:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/organizations",
    name: "MENU_MASTERDATA_ORGANIZATION",
    component: componentRegistry["masterdata/organization/index"],
    meta: {
      title: "企业组织",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_ORGANIZATION",
      permission: "masterdata:organization:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/purchasing-organizations",
    name: "MENU_MASTERDATA_PURCHASING_ORG",
    component: componentRegistry["masterdata/purchasing-organization/index"],
    meta: {
      title: "采购组织",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_PURCHASING_ORG",
      permission: "masterdata:purchasing-organization:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/plants-receiving",
    name: "MENU_MASTERDATA_PLANT_RECEIVING",
    component: componentRegistry["masterdata/plant-receiving/index"],
    meta: {
      title: "工厂/收货地点",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_PLANT_RECEIVING",
      permission: "masterdata:plant-receiving:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/materials",
    name: "MENU_MASTERDATA_MATERIAL",
    component: componentRegistry["masterdata/material/index"],
    meta: {
      title: "物料",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_MATERIAL",
      permission: "masterdata:material:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/categories",
    name: "MENU_MASTERDATA_CATEGORY",
    component: componentRegistry["masterdata/category/index"],
    meta: {
      title: "品类",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_CATEGORY",
      permission: "masterdata:category:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/units-currencies-taxes",
    name: "MENU_MASTERDATA_UNIT_CURRENCY_TAX",
    component: componentRegistry["masterdata/unit-currency-tax/index"],
    meta: {
      title: "单位/币种/税码",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_UNIT_CURRENCY_TAX",
      permission: "masterdata:unit-currency-tax:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/delivery-locations",
    name: "MENU_MASTERDATA_DELIVERY_LOCATION",
    component: componentRegistry["masterdata/delivery-location/index"],
    meta: {
      title: "交付地点",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_DELIVERY_LOCATION",
      permission: "masterdata:delivery-location:view",
      requiresAuth: true,
    },
  },
  {
    path: "/master-data/external-mappings",
    name: "MENU_MASTERDATA_EXTERNAL_MAPPING",
    component: componentRegistry["masterdata/external-mapping/index"],
    meta: {
      title: "外围映射",
      domainLabel: "基础数据中心",
      domainCode: "masterdata",
      menuCode: "MENU_MASTERDATA_EXTERNAL_MAPPING",
      permission: "masterdata:external-mapping:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/users",
    name: "MENU_SYSTEM_USER",
    component: componentRegistry["system/user/index"],
    meta: {
      title: "用户",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_USER",
      permission: "system:user:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/roles",
    name: "MENU_SYSTEM_ROLE",
    component: componentRegistry["system/role/index"],
    meta: {
      title: "角色与挂载用户",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_ROLE",
      permission: "system:role:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/permissions",
    name: "MENU_SYSTEM_PERMISSION",
    component: componentRegistry["system/permission/index"],
    meta: {
      title: "权限与数据域",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_PERMISSION",
      permission: "system:permission:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/workflows",
    name: "MENU_SYSTEM_WORKFLOW",
    component: componentRegistry["system/workflow/index"],
    meta: {
      title: "流程",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_WORKFLOW",
      permission: "system:workflow:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/dictionaries-parameters",
    name: "MENU_SYSTEM_DICTIONARY_PARAMETER",
    component: componentRegistry["system/dictionary-parameter/index"],
    meta: {
      title: "字典参数",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_DICTIONARY_PARAMETER",
      permission: "system:dictionary-parameter:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/templates-attachments",
    name: "MENU_SYSTEM_TEMPLATE_ATTACHMENT",
    component: componentRegistry["system/template-attachment/index"],
    meta: {
      title: "模板附件",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_TEMPLATE_ATTACHMENT",
      permission: "system:template-attachment:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/messages",
    name: "MENU_SYSTEM_MESSAGE",
    component: componentRegistry["system/message/index"],
    meta: {
      title: "消息",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_MESSAGE",
      permission: "system:message:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/audit-logs",
    name: "MENU_SYSTEM_AUDIT_LOG",
    component: componentRegistry["system/audit-log/index"],
    meta: {
      title: "审计日志",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_AUDIT_LOG",
      permission: "system:audit-log:view",
      requiresAuth: true,
    },
  },
  {
    path: "/system/integrations-jobs",
    name: "MENU_SYSTEM_INTEGRATION_JOB",
    component: componentRegistry["system/integration-job/index"],
    meta: {
      title: "接口与任务监控",
      domainLabel: "系统管理",
      domainCode: "system",
      menuCode: "MENU_SYSTEM_INTEGRATION_JOB",
      permission: "system:integration-job:view",
      requiresAuth: true,
    },
  },
]

