upstream srm_backend { server backend:8080; }
upstream srm_internal_web { server internal-web:80; }
upstream srm_supplier_web { server supplier-web:80; }

server {
  listen 80;
  server_name _;
  client_max_body_size 10m;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location /api/ {
    proxy_pass http://srm_backend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Id $request_id;
  }

  location /actuator/ {
    proxy_pass http://srm_backend;
    proxy_set_header Host $host;
  }

  location /supplier/ {
    proxy_pass http://srm_supplier_web/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location / {
    proxy_pass http://srm_internal_web;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }
}
