<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox, type UploadFile } from 'element-plus'
import { internalApi } from '../../../api/internal-api'
import { randomTraceId } from '@srm/api-client'
import { usePermission } from '../../../composables/usePermission'

interface TemplateItem {id:number;templateCode:string;templateName:string;purpose:string|null;domainCode:string;templateVersion:number;attachmentId:number|null;status:'DRAFT'|'PUBLISHED'|'INACTIVE';createdAt:string}
interface Attachment {id:number}
interface Page<T>{items:T[];total:number}
interface BatchJob {id:number;jobType:'IMPORT'|'EXPORT';objectType:string;status:string;totalCount:number;successCount:number;failCount:number;progressPercent:number;attachmentId:number|null;resultAttachmentId:number|null;createdBy:string;createdAt:string}
interface BatchError {id:number;rowNumber:number|null;fieldName:string|null;errorCode:string;errorMessage:string}

const tab=ref<'templates'|'jobs'>('templates')
const rows=ref<TemplateItem[]>([]);const loading=ref(false);const page=ref(1);const pageSize=ref(20);const total=ref(0);const filter=ref('')
const dialog=ref(false);const saving=ref(false);const selectedFile=ref<File|null>(null);const form=reactive({templateCode:'',templateName:'',purpose:'',domainCode:'masterdata'})
const batchRows=ref<BatchJob[]>([]);const batchLoading=ref(false);const batchPage=ref(1);const batchPageSize=ref(20);const batchTotal=ref(0);const batchType=ref('')
const batchDialog=ref(false);const batchMode=ref<'IMPORT'|'EXPORT'>('IMPORT');const batchFile=ref<File|null>(null);const batchForm=reactive({objectType:'MATERIAL',idempotencyKey:''})
const errorsVisible=ref(false);const errors=ref<BatchError[]>([])
const objectTypes=['PURCHASING_ORGANIZATION','DELIVERY_LOCATION','CATEGORY','UNIT','CURRENCY','TAX_CODE','MATERIAL','EXTERNAL_MAPPING']
const canCreate=usePermission('system:document-template:create');const canUpdate=usePermission('system:document-template:update');const canPublish=usePermission('system:document-template:publish');const canDisable=usePermission('system:document-template:disable');const canDownload=usePermission('system:document-template:download')
const canImport=usePermission('system:batch-job:import');const canExport=usePermission('system:batch-job:export');const canRetry=usePermission('system:batch-job:retry')

async function loadTemplates(){loading.value=true;try{const q=new URLSearchParams({page:String(page.value),pageSize:String(pageSize.value)});if(filter.value)q.set('templateCode',filter.value);const r=await internalApi.get<Page<TemplateItem>>('/system/document-templates?'+q);rows.value=r.items;total.value=r.total}catch(e:unknown){rows.value=[];ElMessage.error((e as Error).message||'加载失败')}finally{loading.value=false}}
async function loadJobs(){batchLoading.value=true;try{const q=new URLSearchParams({page:String(batchPage.value),pageSize:String(batchPageSize.value)});if(batchType.value)q.set('objectType',batchType.value);const r=await internalApi.get<Page<BatchJob>>('/system/batch-jobs?'+q);batchRows.value=r.items;batchTotal.value=r.total}catch(e:unknown){batchRows.value=[];ElMessage.error((e as Error).message||'加载任务失败')}finally{batchLoading.value=false}}
function changeTab(){if(tab.value==='jobs')loadJobs();else loadTemplates()}
function openCreate(){Object.assign(form,{templateCode:'',templateName:'',purpose:'',domainCode:'masterdata'});selectedFile.value=null;dialog.value=true}
function selectFile(file:UploadFile){selectedFile.value=file.raw??null}
async function create(){saving.value=true;try{const item=await internalApi.post<TemplateItem>('/system/document-templates',form);if(selectedFile.value){const body=new FormData();body.append('file',selectedFile.value);body.append('ownerType','DOCUMENT_TEMPLATE');body.append('ownerId',String(item.id));const attachment=await internalApi.request<Attachment>('/system/attachments',{method:'POST',body});await internalApi.request('/system/document-templates/'+item.id+'/attachment',{method:'PUT',body:{attachmentId:attachment.id}})}dialog.value=false;ElMessage.success('模板草稿已创建');loadTemplates()}catch(e:unknown){ElMessage.error((e as Error).message||'创建失败')}finally{saving.value=false}}
async function publish(row:TemplateItem){try{await ElMessageBox.confirm('发布后该版本不可修改，确认发布？');await internalApi.post('/system/document-templates/'+row.id+'/publish');ElMessage.success('已发布');loadTemplates()}catch(e){void e}}
async function disable(row:TemplateItem){try{await ElMessageBox.confirm('确认停用该模板版本？');await internalApi.post('/system/document-templates/'+row.id+'/disable');ElMessage.success('已停用');loadTemplates()}catch(e){void e}}
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
async function downloadTemplate(row:TemplateItem){try{saveBlob(await internalApi.download('/system/document-templates/'+row.id+'/download'),`${row.templateCode}-v${row.templateVersion}`)}catch(e:unknown){ElMessage.error((e as Error).message||'下载失败')}}
function openBatch(mode:'IMPORT'|'EXPORT'){batchMode.value=mode;batchFile.value=null;const trace=randomTraceId();Object.assign(batchForm,{objectType:'MATERIAL',idempotencyKey:`${trace.slice(0,8)}-${trace.slice(8,12)}-${trace.slice(12,16)}-${trace.slice(16,20)}-${trace.slice(20)}`});batchDialog.value=true}
function selectBatchFile(file:UploadFile){batchFile.value=file.raw??null}
async function downloadCsvTemplate(){try{saveBlob(await internalApi.download('/system/batch-jobs/import-template?objectType='+batchForm.objectType),batchForm.objectType.toLowerCase()+'-template.csv')}catch(e:unknown){ElMessage.error((e as Error).message||'模板下载失败')}}
async function startBatch(){saving.value=true;try{if(batchMode.value==='IMPORT'){if(!batchFile.value)throw new Error('请选择 CSV 文件');const body=new FormData();body.append('objectType',batchForm.objectType);body.append('idempotencyKey',batchForm.idempotencyKey);body.append('file',batchFile.value);await internalApi.request('/system/batch-jobs/imports',{method:'POST',body})}else await internalApi.post('/system/batch-jobs/exports',batchForm);batchDialog.value=false;tab.value='jobs';ElMessage.success('任务已提交');loadJobs()}catch(e:unknown){ElMessage.error((e as Error).message||'任务提交失败')}finally{saving.value=false}}
async function retryJob(row:BatchJob){try{await ElMessageBox.confirm('确认重试该失败任务？');await internalApi.post('/system/batch-jobs/'+row.id+'/retry');ElMessage.success('已重试');loadJobs()}catch(e){void e}}
async function showErrors(row:BatchJob){try{errors.value=await internalApi.get<BatchError[]>('/system/batch-jobs/'+row.id+'/errors');errorsVisible.value=true}catch(e:unknown){ElMessage.error((e as Error).message||'错误明细加载失败')}}
async function downloadResult(row:BatchJob){if(!row.resultAttachmentId)return;try{saveBlob(await internalApi.download('/system/attachments/'+row.resultAttachmentId+'/download'),`batch-${row.id}-result.csv`)}catch(e:unknown){ElMessage.error((e as Error).message||'结果下载失败')}}
onMounted(loadTemplates)
</script>

<template><section class="page"><el-card><el-tabs v-model="tab" @tab-change="changeTab"><el-tab-pane label="文档模板" name="templates"/><el-tab-pane label="导入导出任务" name="jobs"/></el-tabs>
<template v-if="tab==='templates'"><div class="toolbar"><el-input v-model="filter" clearable placeholder="模板编码" style="width:220px" @keyup.enter="loadTemplates"/><el-button type="primary" @click="loadTemplates">查询</el-button><el-button v-if="canCreate" type="primary" style="margin-left:auto" @click="openCreate">新建版本</el-button></div><el-table v-loading="loading" :data="rows" border stripe style="margin-top:16px"><el-table-column prop="templateCode" label="模板编码" width="170"/><el-table-column prop="templateName" label="模板名称" min-width="180"/><el-table-column prop="domainCode" label="领域" width="110"/><el-table-column prop="templateVersion" label="版本" width="70"/><el-table-column prop="status" label="状态" width="100"/><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="210"><template #default="{row}"><el-button v-if="canDownload&&row.attachmentId" link type="primary" @click="downloadTemplate(row)">下载</el-button><el-button v-if="canPublish&&row.status==='DRAFT'&&row.attachmentId" link type="success" @click="publish(row)">发布</el-button><el-button v-if="canDisable&&row.status!=='INACTIVE'" link type="warning" @click="disable(row)">停用</el-button><span v-if="canUpdate&&row.status==='DRAFT'&&!row.attachmentId" class="hint">待上传</span></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="total" layout="total, sizes, prev, pager, next" @current-change="loadTemplates" @size-change="loadTemplates"/></div></template>
<template v-else><div class="toolbar"><el-select v-model="batchType" clearable placeholder="对象类型" style="width:220px" @change="loadJobs"><el-option v-for="x in objectTypes" :key="x" :label="x" :value="x"/></el-select><el-button @click="loadJobs">刷新</el-button><el-button v-if="canImport" type="primary" style="margin-left:auto" @click="openBatch('IMPORT')">导入</el-button><el-button v-if="canExport" type="success" @click="openBatch('EXPORT')">导出</el-button></div><el-table v-loading="batchLoading" :data="batchRows" border stripe style="margin-top:16px"><el-table-column prop="id" label="任务ID" width="80"/><el-table-column prop="jobType" label="类型" width="90"/><el-table-column prop="objectType" label="对象" width="190"/><el-table-column prop="status" label="状态" width="130"/><el-table-column label="数量" width="160"><template #default="{row}">{{row.successCount||0}} 成功 / {{row.failCount||0}} 失败 / {{row.totalCount||0}} 总计</template></el-table-column><el-table-column prop="createdBy" label="创建人" width="120"/><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="190"><template #default="{row}"><el-button v-if="row.failCount" link type="danger" @click="showErrors(row)">错误明细</el-button><el-button v-if="row.resultAttachmentId" link type="primary" @click="downloadResult(row)">结果文件</el-button><el-button v-if="canRetry&&row.status==='FAILED'" link type="warning" @click="retryJob(row)">重试</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="batchPage" v-model:page-size="batchPageSize" :total="batchTotal" layout="total, sizes, prev, pager, next" @current-change="loadJobs" @size-change="loadJobs"/></div></template></el-card>
<el-dialog v-model="dialog" title="新建模板版本" width="520px"><el-form :model="form" label-width="90px"><el-form-item label="模板编码"><el-input v-model="form.templateCode"/></el-form-item><el-form-item label="模板名称"><el-input v-model="form.templateName"/></el-form-item><el-form-item label="所属领域"><el-input v-model="form.domainCode"/></el-form-item><el-form-item label="用途"><el-input v-model="form.purpose"/></el-form-item><el-form-item label="模板文件"><el-upload :auto-upload="false" :limit="1" :on-change="selectFile"><el-button>选择文件</el-button></el-upload></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!selectedFile" @click="create">创建草稿</el-button></template></el-dialog>
<el-dialog v-model="batchDialog" :title="batchMode==='IMPORT'?'提交导入任务':'提交导出任务'" width="520px"><el-form :model="batchForm" label-width="90px"><el-form-item label="对象类型"><el-select v-model="batchForm.objectType" style="width:100%"><el-option v-for="x in objectTypes" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="幂等键"><el-input v-model="batchForm.idempotencyKey"/></el-form-item><template v-if="batchMode==='IMPORT'"><el-form-item label="标准模板"><el-button link type="primary" @click="downloadCsvTemplate">下载当前 CSV 模板</el-button></el-form-item><el-form-item label="导入文件"><el-upload accept=".csv,text/csv" :auto-upload="false" :limit="1" :on-change="selectBatchFile"><el-button>选择 CSV</el-button></el-upload></el-form-item></template></el-form><template #footer><el-button @click="batchDialog=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="batchMode==='IMPORT'&&!batchFile" @click="startBatch">提交</el-button></template></el-dialog>
<el-dialog v-model="errorsVisible" title="行级错误明细" width="760px"><el-table :data="errors" border><el-table-column prop="rowNumber" label="行号" width="80"/><el-table-column prop="fieldName" label="字段" width="130"/><el-table-column prop="errorCode" label="错误码" width="150"/><el-table-column prop="errorMessage" label="错误原因" min-width="260"/></el-table></el-dialog></section></template>
<style scoped>.page{padding:24px}.toolbar{display:flex;gap:12px;align-items:center}.pager{display:flex;justify-content:flex-end;margin-top:16px}.hint{color:#909399}</style>
