<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { internalApi } from '../../../api/internal-api'
import { usePermission } from '../../../composables/usePermission'

type OrgType='PLANT'|'WAREHOUSE'
interface OrgNode {id:number;orgCode:string;orgName:string;orgType:string;sortOrder:number;status:'ACTIVE'|'INACTIVE';level:number;children:OrgNode[]}
interface PlantInfo {id:number;plantCode:string;plantName:string;timezone:string|null;country:string|null;address:string|null}
interface WarehouseInfo {id:number;warehouseCode:string;warehouseName:string;plantId:number;warehouseType:string|null}
interface OrgDetail extends OrgNode {parentId:number|null;description:string|null;version:number;plant:PlantInfo|null;warehouse:WarehouseInfo|null}

const loading=ref(false);const source=ref<OrgNode[]>([]);const page=ref(1);const pageSize=ref(20)
const filter=reactive({keyword:'',orgType:'' as ''|OrgType,status:''})
const dialog=ref(false);const saving=ref(false);const mode=ref<'create'|'edit'>('create');const parentOptions=ref<OrgDetail[]>([])
const form=reactive({id:0,orgCode:'',orgName:'',orgType:'PLANT' as OrgType,parentId:null as number|null,sortOrder:0,description:'',version:0,plantCode:'',plantName:'',timezone:'Asia/Shanghai',country:'CN',address:'',warehouseCode:'',warehouseName:'',plantId:null as number|null,warehouseType:'RECEIVING'})
const canCreate=usePermission('masterdata:organization:create');const canUpdate=usePermission('masterdata:organization:update');const canEnable=usePermission('masterdata:organization:enable');const canDisable=usePermission('masterdata:organization:disable')
function flatten(nodes:OrgNode[]):OrgNode[]{return nodes.flatMap(n=>[n,...flatten(n.children??[])])}
async function load(){loading.value=true;try{source.value=flatten(await internalApi.get<OrgNode[]>('/master-data/organizations')).filter(x=>x.orgType==='PLANT'||x.orgType==='WAREHOUSE')}catch(e:unknown){source.value=[];ElMessage.error((e as Error).message||'加载失败')}finally{loading.value=false}}
const filtered=computed(()=>source.value.filter(r=>(!filter.orgType||r.orgType===filter.orgType)&&(!filter.status||r.status===filter.status)&&(!filter.keyword||`${r.orgCode} ${r.orgName}`.toLowerCase().includes(filter.keyword.toLowerCase()))))
const rows=computed(()=>filtered.value.slice((page.value-1)*pageSize.value,page.value*pageSize.value))
async function loadParents(type:OrgType){try{parentOptions.value=await internalApi.get<OrgDetail[]>('/master-data/organizations/valid-parents?orgType='+type)}catch{parentOptions.value=[]}}
function openCreate(type:OrgType){mode.value='create';Object.assign(form,{id:0,orgCode:'',orgName:'',orgType:type,parentId:null,sortOrder:0,description:'',version:0,plantCode:'',plantName:'',timezone:'Asia/Shanghai',country:'CN',address:'',warehouseCode:'',warehouseName:'',plantId:null,warehouseType:'RECEIVING'});loadParents(type);dialog.value=true}
function onParentChange(parentId:number|null){const parent=parentOptions.value.find(item=>item.id===parentId);form.plantId=form.orgType==='WAREHOUSE'?parent?.plant?.id??null:null}
async function openEdit(row:OrgNode){try{const d=await internalApi.get<OrgDetail>('/master-data/organizations/'+row.id);mode.value='edit';Object.assign(form,{id:d.id,orgCode:d.orgCode,orgName:d.orgName,orgType:d.orgType as OrgType,parentId:d.parentId,sortOrder:d.sortOrder,description:d.description??'',version:d.version,plantCode:d.plant?.plantCode??'',plantName:d.plant?.plantName??'',timezone:d.plant?.timezone??'Asia/Shanghai',country:d.plant?.country??'CN',address:d.plant?.address??'',warehouseCode:d.warehouse?.warehouseCode??'',warehouseName:d.warehouse?.warehouseName??'',plantId:d.warehouse?.plantId??null,warehouseType:d.warehouse?.warehouseType??'RECEIVING'});dialog.value=true}catch(e:unknown){ElMessage.error((e as Error).message||'详情加载失败')}}
function requestBody(){const common={orgCode:form.orgCode,orgName:form.orgName,orgType:form.orgType,parentId:form.parentId,sortOrder:form.sortOrder,description:form.description,version:form.version};return form.orgType==='PLANT'?{...common,plantCode:form.plantCode,plantName:form.plantName,timezone:form.timezone,country:form.country,address:form.address}:{...common,warehouseCode:form.warehouseCode,warehouseName:form.warehouseName,plantId:form.plantId,warehouseType:form.warehouseType}}
async function save(){saving.value=true;try{if(mode.value==='create')await internalApi.post('/master-data/organizations',requestBody());else await internalApi.request('/master-data/organizations/'+form.id,{method:'PUT',body:requestBody()});dialog.value=false;ElMessage.success('保存成功');load()}catch(e:unknown){ElMessage.error((e as Error).message||'保存失败')}finally{saving.value=false}}
async function setStatus(row:OrgNode,action:'enable'|'disable'){try{await ElMessageBox.confirm(`确认${action==='enable'?'启用':'停用'} ${row.orgName}？`);await internalApi.post(`/master-data/organizations/${row.id}/${action}`);ElMessage.success('操作成功');load()}catch(e){void e}}
onMounted(load)
</script>
<template><section class="page"><el-card><div class="toolbar"><el-input v-model="filter.keyword" clearable placeholder="名称或编码" style="width:220px"/><el-select v-model="filter.orgType" clearable placeholder="类型" style="width:130px"><el-option label="工厂" value="PLANT"/><el-option label="收货仓库" value="WAREHOUSE"/></el-select><el-select v-model="filter.status" clearable placeholder="状态" style="width:120px"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select><el-dropdown v-if="canCreate" style="margin-left:auto" @command="openCreate"><el-button type="primary">新建</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="PLANT">工厂</el-dropdown-item><el-dropdown-item command="WAREHOUSE">收货仓库</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div><el-table v-loading="loading" :data="rows" border stripe style="margin-top:16px"><el-table-column prop="orgCode" label="编码" width="150"/><el-table-column prop="orgName" label="名称" min-width="190"/><el-table-column label="类型" width="110"><template #default="{row}">{{row.orgType==='PLANT'?'工厂':'收货仓库'}}</template></el-table-column><el-table-column prop="level" label="层级" width="80"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{row.status==='ACTIVE'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="170"><template #default="{row}"><el-button v-if="canUpdate" link type="primary" @click="openEdit(row)">详情/编辑</el-button><el-button v-if="row.status==='ACTIVE'?canDisable:canEnable" link :type="row.status==='ACTIVE'?'warning':'success'" @click="setStatus(row,row.status==='ACTIVE'?'disable':'enable')">{{row.status==='ACTIVE'?'停用':'启用'}}</el-button></template></el-table-column></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="pageSize" :total="filtered.length" layout="total, sizes, prev, pager, next"/></div></el-card>
<el-dialog v-model="dialog" :title="`${mode==='create'?'新增':'编辑'}${form.orgType==='PLANT'?'工厂':'收货仓库'}`" width="560px"><el-form :model="form" label-width="100px"><el-form-item label="组织编码" required><el-input v-model="form.orgCode" :disabled="mode==='edit'"/></el-form-item><el-form-item label="组织名称" required><el-input v-model="form.orgName"/></el-form-item><el-form-item v-if="mode==='create'" label="上级组织" required><el-select v-model="form.parentId" filterable style="width:100%" @change="onParentChange"><el-option v-for="p in parentOptions" :key="p.id" :label="`${p.orgName} (${p.orgCode})`" :value="p.id"/></el-select></el-form-item><template v-if="form.orgType==='PLANT'"><el-form-item label="工厂编码" required><el-input v-model="form.plantCode" :disabled="mode==='edit'"/></el-form-item><el-form-item label="工厂名称" required><el-input v-model="form.plantName"/></el-form-item><el-form-item label="时区"><el-input v-model="form.timezone"/></el-form-item><el-form-item label="国家"><el-input v-model="form.country"/></el-form-item><el-form-item label="地址"><el-input v-model="form.address" type="textarea"/></el-form-item></template><template v-else><el-form-item label="仓库编码" required><el-input v-model="form.warehouseCode" :disabled="mode==='edit'"/></el-form-item><el-form-item label="仓库名称" required><el-input v-model="form.warehouseName"/></el-form-item><el-form-item label="所属工厂"><el-input :model-value="parentOptions.find(item=>item.id===form.parentId)?.orgName??String(form.plantId??'')" disabled/></el-form-item><el-form-item label="仓库类型"><el-input v-model="form.warehouseType"/></el-form-item></template></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!form.orgCode||!form.orgName||mode==='create'&&!form.parentId" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.page{padding:24px}.toolbar{display:flex;gap:12px;align-items:center}.pager{display:flex;justify-content:flex-end;margin-top:16px}</style>
