import { createRequire } from 'node:module'
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join, resolve } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const { diffSpecs } = require('openapi-diff')
const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const writeMode = process.argv.includes('--write')
const establishBaseline = process.argv.includes('--establish-baseline')
const contractRoot = resolve(root, 'docs/04-接口与数据设计/openapi')
const generatedRoot = resolve(root, 'backend/target/generated-openapi')
const documentationRoot = resolve(root, 'backend/target/openapi-docs')
const typesRoot = resolve(root, 'frontend/packages/shared-types/src/generated')
const clientsRoot = resolve(root, 'frontend/packages/api-client/src/generated')
const redocly = resolve(root, 'node_modules/.bin/redocly')
const openapiTypescript = resolve(root, 'node_modules/.bin/openapi-typescript')
const domains = [
  {
    code: 'internal',
    typeName: 'InternalApiPaths',
    clientName: 'createInternalContractClient',
  },
  {
    code: 'supplier',
    typeName: 'SupplierApiPaths',
    clientName: 'createSupplierContractClient',
  },
]

const fail = (message) => {
  console.error(message)
  process.exit(1)
}

const normalizedJson = (path) => `${JSON.stringify(JSON.parse(readFileSync(path, 'utf8')), null, 2)}\n`

const run = (command, args) => {
  const result = spawnSync(command, args, { cwd: root, encoding: 'utf8', stdio: 'pipe' })
  if (result.status !== 0) {
    process.stderr.write(result.stdout ?? '')
    process.stderr.write(result.stderr ?? '')
    fail(`命令失败: ${basename(command)} ${args.join(' ')}`)
  }
  if (result.stdout) process.stdout.write(result.stdout)
}

const clientSource = ({ typeName, clientName }) => `/* Generated by scripts/check-openapi.mjs. Do not edit manually. */
import createClient from 'openapi-fetch'
import type { ${typeName} } from '@srm/shared-types'

export const ${clientName} = (baseUrl: string) =>
  createClient<${typeName}>({ baseUrl })
`

const generateTypes = (specification, output) => {
  mkdirSync(dirname(output), { recursive: true })
  run(openapiTypescript, [specification, '--output', output, '--immutable'])
}

const ensureGeneratedContracts = () => {
  for (const domain of domains) {
    const generated = resolve(generatedRoot, `${domain.code}-api.json`)
    if (!existsSync(generated)) {
      fail(`缺少Springdoc实际导出契约: ${generated}；请先运行后端测试。`)
    }
  }
}

const updateArtifacts = () => {
  mkdirSync(contractRoot, { recursive: true })
  mkdirSync(resolve(contractRoot, 'baseline'), { recursive: true })
  mkdirSync(typesRoot, { recursive: true })
  mkdirSync(clientsRoot, { recursive: true })
  for (const domain of domains) {
    const generated = resolve(generatedRoot, `${domain.code}-api.json`)
    const contract = resolve(contractRoot, `${domain.code}-api.json`)
    const baseline = resolve(contractRoot, 'baseline', `${domain.code}-api.json`)
    writeFileSync(contract, normalizedJson(generated))
    if (!existsSync(baseline) || establishBaseline) {
      writeFileSync(baseline, normalizedJson(generated))
    }
    generateTypes(contract, resolve(typesRoot, `${domain.code}-api.ts`))
    writeFileSync(resolve(clientsRoot, `${domain.code}-api-client.ts`), clientSource(domain))
  }
  console.log(
    establishBaseline
      ? 'OpenAPI契约、兼容基线、共享TypeScript类型和API客户端已更新。'
      : 'OpenAPI契约、共享TypeScript类型和API客户端已更新；既有兼容基线保持不变。',
  )
}

const validateContracts = async () => {
  const temporary = mkdtempSync(join(tmpdir(), 'srm-openapi-'))
  try {
    for (const domain of domains) {
      const generated = resolve(generatedRoot, `${domain.code}-api.json`)
      const contract = resolve(contractRoot, `${domain.code}-api.json`)
      const baseline = resolve(contractRoot, 'baseline', `${domain.code}-api.json`)
      const committedType = resolve(typesRoot, `${domain.code}-api.ts`)
      const committedClient = resolve(clientsRoot, `${domain.code}-api-client.ts`)
      for (const required of [contract, baseline, committedType, committedClient]) {
        if (!existsSync(required)) fail(`缺少OpenAPI受控产物: ${required}`)
      }
      if (normalizedJson(generated) !== normalizedJson(contract)) {
        fail(`${domain.code} Springdoc导出与受控OpenAPI契约不一致；请评审后运行 npm run openapi:update。`)
      }

      const diff = await diffSpecs({
        sourceSpec: {
          content: readFileSync(baseline, 'utf8'),
          location: baseline,
          format: 'openapi3',
        },
        destinationSpec: {
          content: readFileSync(contract, 'utf8'),
          location: contract,
          format: 'openapi3',
        },
      })
      if (diff.breakingDifferencesFound) {
        console.error(JSON.stringify(diff.breakingDifferences, null, 2))
        fail(`${domain.code} OpenAPI包含相对兼容基线的破坏性变更。`)
      }

      const temporaryType = resolve(temporary, `${domain.code}-api.ts`)
      generateTypes(contract, temporaryType)
      if (readFileSync(temporaryType, 'utf8') !== readFileSync(committedType, 'utf8')) {
        fail(`${domain.code} 共享TypeScript类型与OpenAPI契约不一致。`)
      }
      if (clientSource(domain) !== readFileSync(committedClient, 'utf8')) {
        fail(`${domain.code} 生成API客户端与模板不一致。`)
      }
    }

    run(redocly, [
      'lint',
      ...domains.map(({ code }) => resolve(contractRoot, `${code}-api.json`)),
      '--config',
      resolve(contractRoot, 'redocly.yaml'),
      '--format',
      'stylish',
    ])

    mkdirSync(documentationRoot, { recursive: true })
    for (const { code } of domains) {
      run(redocly, [
        'build-docs',
        resolve(contractRoot, `${code}-api.json`),
        '--output',
        resolve(documentationRoot, `${code}-api.html`),
      ])
    }
    console.log('OpenAPI双域导出、规范校验、破坏性变更、静态文档及TypeScript/API客户端检查通过。')
  } finally {
    rmSync(temporary, { recursive: true, force: true })
  }
}

ensureGeneratedContracts()
if (writeMode) updateArtifacts()
await validateContracts()
